// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AnalyzeAudio(arg1) {
  return window['go']['main']['App']['AnalyzeAudio'](arg1);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetArtistDiscography(arg1) {
  return window['go']['main']['App']['GetArtistDiscography'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSpotifyPlaylists() {
  return window['go']['main']['App']['GetSpotifyPlaylists']();
}

export function GetSpotifyStatus() {
  return window['go']['main']['App']['GetSpotifyStatus']();
}

export function LoginSpotify() {
  return window['go']['main']['App']['LoginSpotify']();
}

export function LogoutSpotify() {
  return window['go']['main']['App']['LogoutSpotify']();
}

export function PickAnalyzerFiles() {
  return window['go']['main']['App']['PickAnalyzerFiles']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanFolder(arg1) {
  return window['go']['main']['App']['ScanFolder'](arg1);
}

export function SetSpotifyCookie(arg1) {
  return window['go']['main']['App']['SetSpotifyCookie'](arg1);
}

export function SetSpotifyToken(arg1) {
  return window['go']['main']['App']['SetSpotifyToken'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
